<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_node_view()
 */

function feature_add_multimedia_to_quiz_node_view($node, $view_mode, $langcode) {
  /*dpm($node);*/
  if ($node->type == 'short_answer'){
    if (isset($node->field_son)){
      /*dpm($node->type);
      dpm($node->correct_answer_evaluation);*/
    }

  }
  /*$node->content['my_additional_field'] = array(
    '#markup' => $additional_field,
    '#weight' => 10,
    '#theme' => 'mymodule_my_additional_field',
  );*/
}
/**
 * Implements hook_form_FORM_ID_alter()
 */
/*function feature_add_multimedia_to_quiz_form_quiz_question_answering_form_alter(&$form, &$form_state, $form_id) {
  // Print custom fields on the question page during the quiz.
  foreach ($form['questions'] as $node_key => $node_value) {
    $qnode = node_load($form['questions'][$node_key]['header']['body']['#object']->nid);
  }

  $field_source_url = !empty($qnode->field_source[LANGUAGE_NONE][0]['url']) ? $qnode->field_source[LANGUAGE_NONE][0]['url'] : '';
  $field_source_title = !empty($qnode->field_source[LANGUAGE_NONE][0]['title']) ? $qnode->field_source[LANGUAGE_NONE][0]['title'] : $field_source_url;
  $field_source = l($field_source_title, $field_source_url);

  $form['navigation']['#prefix'] = theme('question_link', array(
    'field_source' => $field_source,
  ));
}*/

/**
 * Implements hook_theme()
 *
 * @return array
 */
/*function feature_add_multimedia_to_quiz_theme() {
  $items = array();
  $theme_path = drupal_get_path('theme', 'my_theme') . '/templates';

  $items['question_link'] = array(
    'path' => $theme_path,
    'template' => 'question-link',
    'variables' => array(
      'field_source' => NULL,
    ),
  );

  return $items;
}*/